### ISSUE TITLE
`genstack -s` raises DeprecationWarning

### ISSUE THREAD

**Issue by lh-astro** [bwkeller/PASTA#1]
When using `genstack -s` is raises a DeprecationWarning. Looking into the source code (stampy.py", line 117) it does not seem to be implemented. Is this correct?

```
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to 21.443900 from OBSGEO-[XYZ].
Set OBSGEO-B to   -30.713200 from OBSGEO-[XYZ].
Set OBSGEO-H to     1046.994 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
Traceback (most recent call last):
  File "/usr/local/bin/genstack", line 416, in <module>
    options.subtract_background, options.fakesource))
  File "/usr/local/bin/genstack", line 152, in stack_build
    fitswcs=mywcs, savewcs=save)
  File "/usr/local/lib/python3.6/dist-packages/stampy.py", line 117, in __init__
    raise DeprecationWarning
DeprecationWarning
```

**Comment by bwkeller** [comment]
Hi Lennart,

I'd like to try and reproduce this, would you be able to send me a tarball with the script you are using to call genstack.py, as well as a sample image & source list for me to run and try and debug the problem?  You can use http://transfer.sh/ if the tarball is less than 10 Gb.  I only should need a handful of sources and one of the image tiles to reproduce the error.  

I think the issue is that astropy's WCS API is returning None because of an issue with the header, but I can't be sure without trying it myself.

**Comment by lh-astro** [comment]
Hi Ben,
I've sent you an email to your university address. Did it reach you? (I had issues getting my email though to the Calgary server).

**Comment by bwkeller** [comment]
I believe commit 2de18ae should fix this.  Let me know if you are still having trouble!
